version: '3.4'

services:
  userservice:
    build:
      context: ./UserService
    ports:
      - "5001:80" # Puerto expuesto para el servicio de usuario
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__UserDb=Server=LAPTOP-BEDCLS7D;Database=TaskManagerDB;User Id=TaskManagerDB;Password=TaskManagerDB;Encrypt=False; # Cadena de conexión a la base de datos

  taskservice:
    build:
      context: ./TaskService
    ports:
      - "5002:80" # Puerto expuesto para el servicio de tareas
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TaskDb=Server=LAPTOP-BEDCLS7D;Database=TaskManagerDB;User Id=TaskManagerDB;Password=TaskManagerDB;Encrypt=False; # Cadena de conexión a la base de datos

  db:
    image: mcr.microsoft.com/mssql/server # Imagen de SQL Server
    environment:
      SA_PASSWORD: Niva2033$ # Contraseña para el usuario SA
      ACCEPT_EULA: Y # Acepta el EULA
    ports:
      - "1433:1433" # Puerto expuesto para SQL Server
