version: '3.4'

services:
  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=TaskManagerDB;User Id=TaskMangerDB;Password=TaskMangerDB;

  taskservice:
    build:
      context: ./TaskService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=TaskManagerDB;User Id=TaskMangerDB;Password=TaskMangerDB;
