apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  type: LoadBalancer  # O ClusterIP, NodePort según las necesidades
  selector:
    app: userservice  # Debe coincidir con las etiquetas del Deployment
  ports:
    - port: 80        # Puerto en el que el servicio estará disponible
      targetPort: 80  # Puerto en el contenedor
